### ISSUE TITLE
Looks like wrong coloring

### ISSUE THREAD

**Issue by afeblot** [skorokithakis/tbvaccine#20]
On MacOS High Sierra, with system Python 2.7.10, tbvaccine 0.2.2 coloring does not look correct. At least not like your examples:
![tbvaccine](https://user-images.githubusercontent.com/12073123/42413176-1b11fd44-821b-11e8-9cac-a7af93f86d84.png)

**Comment by skorokithakis** [comment]
It looks right to me, `script.py` and `procrunner.py` look like they were detected as "your" code and expanded on. Is that not right?

**Comment by afeblot** [comment]
It's not about "isolated" code, which I've not checked, as the entire stack here is in my code. it's rather about local variables lines where "|", "<" and ">" are sometimes red and sometimes white, whereas they are consistently red in your examples.

**Comment by skorokithakis** [comment]
Oh, I see. Hmm, yes, I will have to debug. Thank you!

**Comment by skorokithakis** [comment]
Fixed, thanks!
