### ISSUE TITLE
Support for white background

### ISSUE THREAD

**Issue by avivey** [skorokithakis/tbvaccine#25]
The trace is basically unreadable when using a bright background for the terminal:
![image](https://user-images.githubusercontent.com/1530242/50176432-3484d480-02b4-11e9-8e53-e4b2995768ed.png)

pls add support to an alternative color scheme...

**Comment by skorokithakis** [comment]
Oops, good call. It's not hard to do, we'll just need to add a configuration file.

**Comment by skorokithakis** [comment]
This has been resolved in 21a4934.

**Comment by avivey** [comment]
Thanks. I think envvar would have been simpler, but this works too. 👍
