### ISSUE TITLE
Support force-enable (even when not isatty)

### ISSUE THREAD

**Issue by wataash** [skorokithakis/tbvaccine#28]
Hi, thanks for creating this great library!

I want to use this library in a kubernetes container where stderr is not a tty.
It'll be convenient if we can do force-enabling by setting an environment variable.

**Comment by skorokithakis** [comment]
Sure, that'll be great. Thanks for the PR!

**Comment by wataash** [comment]
Okay, I'll work on this at #29 :)

**Comment by skorokithakis** [comment]
Great, thanks!
