### ISSUE TITLE
Hooked by TBVACCINE=0 is confusing

### ISSUE THREAD

**Issue by wataash** [skorokithakis/tbvaccine#34]
README says `export TBVACCINE=1` hooks tbvaccine, so I expected `export TBVACCINE=0` would not hook, but it did.
I think the hook should be done only if `TBVACCINE` is exactly `1`. (but that's a breaking change...)

**Comment by skorokithakis** [comment]
You are correct, we should do this. If someone set `TBVACCINE` to anything other than 1 to enable it, that's undocumented, and we don't have to support it.
