### ISSUE TITLE
Running tbvaccine on non python file - colors don't work

### ISSUE THREAD

**Issue by szabolcsdombi** [skorokithakis/tbvaccine#6]
By mistake I just called `python -m tbvaccine tox.ini`.

The trace has no colors and it is longer then 100 lines, however calling python directly on a non python file causes only 4 lines for a single exception.

![image](https://cloud.githubusercontent.com/assets/11232402/26205246/76181f2e-3be1-11e7-972e-c145eec63704.png)

It would be great if tbvaccine could detect when a non python file is passed.

**Comment by skorokithakis** [comment]
You aren't meant to be calling `tbvaccine` with files as arguments, though. It should detect when you've passed an argument and give an error message, I agree.

**Comment by skorokithakis** [comment]
Hmm, I can't reproduce this:

~~~
16:53:35 $ python -m tbvaccine tox.ini 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/tbvaccine/tbvaccine/__main__.py", line 23, in <module>
>   code = compile(script_file.read(), script_path, 'exec')
|     __builtins__ = <module '__builtin__' (built-in)>
|     __doc__      = None
|     __file__     = /tmp/tbvaccine/tbvaccine/__main__.py
|     __loader__   = <pkgutil.ImpLoader instance at 0x7f57adb82e60>
|     __name__     = __main__
|     __package__  = tbvaccine
|     os           = <module 'os' from '/usr/lib/python2.7/os.pyc'>
|     script_file  = <closed file 'tox.ini', mode 'r' at 0x7f57adb1e030>
|     script_path  = tox.ini
|     sys          = <module 'sys' (built-in)>
|     tbvaccine    = <module 'tbvaccine' from 'tbvaccine/__init__.pyc'>
SyntaxError: invalid syntax (tox.ini, line 5)
~~~

**Comment by szabolcsdombi** [comment]
I am using windows it seems colors don't work on windows :(

**Comment by szabolcsdombi** [comment]
Colorama works on windows. It changes the cmd.exe settings runtime by calling some winpai functions, here is a [link](https://github.com/tartley/colorama#initialisation).

**Comment by skorokithakis** [comment]
Ah, I see. Unfortunately I don't have a Windows set up, but I'd be grateful if you wanted to submit a PR for this.

**Comment by szabolcsdombi** [comment]
I give it a try.
